/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EpubTestRouteImport } from './routes/epub-test'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated/finances'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedImportDebugRouteImport } from './routes/_authenticated/import-debug'
import { Route as AuthenticatedImportReviewRouteImport } from './routes/_authenticated/import-review'
import { Route as AuthenticatedNemotronTestRouteImport } from './routes/_authenticated/nemotron-test'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses.index'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EpubTestRoute = EpubTestRouteImport.update({
  id: '/epub-test',
  path: '/epub-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportDebugRoute =
  AuthenticatedImportDebugRouteImport.update({
    id: '/import-debug',
    path: '/import-debug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportReviewRoute =
  AuthenticatedImportReviewRouteImport.update({
    id: '/import-review',
    path: '/import-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNemotronTestRoute =
  AuthenticatedNemotronTestRouteImport.update({
    id: '/nemotron-test',
    path: '/nemotron-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/epub-test': typeof EpubTestRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/import': typeof AuthenticatedImportRoute
  '/import-debug': typeof AuthenticatedImportDebugRoute
  '/import-review': typeof AuthenticatedImportReviewRoute
  '/nemotron-test': typeof AuthenticatedNemotronTestRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/epub-test': typeof EpubTestRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/import': typeof AuthenticatedImportRoute
  '/import-debug': typeof AuthenticatedImportDebugRoute
  '/import-review': typeof AuthenticatedImportReviewRoute
  '/nemotron-test': typeof AuthenticatedNemotronTestRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/epub-test': typeof EpubTestRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/import-debug': typeof AuthenticatedImportDebugRoute
  '/_authenticated/import-review': typeof AuthenticatedImportReviewRoute
  '/_authenticated/nemotron-test': typeof AuthenticatedNemotronTestRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/epub-test'
    | '/assignments'
    | '/assistant'
    | '/calendar'
    | '/dashboard'
    | '/finances'
    | '/import'
    | '/import-debug'
    | '/import-review'
    | '/nemotron-test'
    | '/onboarding'
    | '/settings'
    | '/courses/$courseId'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/epub-test'
    | '/assignments'
    | '/assistant'
    | '/calendar'
    | '/dashboard'
    | '/finances'
    | '/import'
    | '/import-debug'
    | '/import-review'
    | '/nemotron-test'
    | '/onboarding'
    | '/settings'
    | '/courses/$courseId'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/epub-test'
    | '/_authenticated/assignments'
    | '/_authenticated/assistant'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/finances'
    | '/_authenticated/import'
    | '/_authenticated/import-debug'
    | '/_authenticated/import-review'
    | '/_authenticated/nemotron-test'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/courses/$courseId'
    | '/_authenticated/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EpubTestRoute: typeof EpubTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epub-test': {
      id: '/epub-test'
      path: '/epub-test'
      fullPath: '/epub-test'
      preLoaderRoute: typeof EpubTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-debug': {
      id: '/_authenticated/import-debug'
      path: '/import-debug'
      fullPath: '/import-debug'
      preLoaderRoute: typeof AuthenticatedImportDebugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-review': {
      id: '/_authenticated/import-review'
      path: '/import-review'
      fullPath: '/import-review'
      preLoaderRoute: typeof AuthenticatedImportReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nemotron-test': {
      id: '/_authenticated/nemotron-test'
      path: '/nemotron-test'
      fullPath: '/nemotron-test'
      preLoaderRoute: typeof AuthenticatedNemotronTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedImportDebugRoute: typeof AuthenticatedImportDebugRoute
  AuthenticatedImportReviewRoute: typeof AuthenticatedImportReviewRoute
  AuthenticatedNemotronTestRoute: typeof AuthenticatedNemotronTestRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedImportDebugRoute: AuthenticatedImportDebugRoute,
  AuthenticatedImportReviewRoute: AuthenticatedImportReviewRoute,
  AuthenticatedNemotronTestRoute: AuthenticatedNemotronTestRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCoursesCourseIdRoute: AuthenticatedCoursesCourseIdRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EpubTestRoute: EpubTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
